### ISSUE TITLE
Kinu Kai2 does not appear.

### ISSUE THREAD

**Issue by Danielosama** [Laforeta/ooi2#13]
Hello,
Ever since today's maintenance adding Kinu Kai2, not only could I not remodel her when playing through OOI, but she does NOT appear on my shiplist, and if I have her on my fleet when logging in through OOI, the game catbombs shortly after.
Any solution?

**Comment by Laforeta** [comment]
Sorry about the hiccup. It is fixed now. The server somehow did not refresh the initialisation data after the update.

**Comment by Danielosama** [comment]
Thanks for the quick fix :)
